//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.dbViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCME.dbViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed number of characters.
        /// </summary>
        public static string AllowedNumberOfCharacters {
            get {
                return ResourceManager.GetString("AllowedNumberOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly job.
        /// </summary>
        public static string AssemblyJob {
            get {
                return ResourceManager.GetString("AssemblyJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly protocol.
        /// </summary>
        public static string AssemblyProtocol {
            get {
                return ResourceManager.GetString("AssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly protocols.
        /// </summary>
        public static string AssemblyProtocols {
            get {
                return ResourceManager.GetString("AssemblyProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITAV.
        /// </summary>
        public static string AverageCurrent {
            get {
                return ResourceManager.GetString("AverageCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user permissions.
        /// </summary>
        public static string BitCalculator {
            get {
                return ResourceManager.GetString("BitCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previously saved list will be loaded from the database instead of the displayed list. Proceed?.
        /// </summary>
        public static string CanReloadList {
            get {
                return ResourceManager.GetString("CanReloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case type.
        /// </summary>
        public static string CaseType {
            get {
                return ResourceManager.GetString("CaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change prohibited.
        /// </summary>
        public static string ChangeProhibited {
            get {
                return ResourceManager.GetString("ChangeProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked
        ///device.
        /// </summary>
        public static string CheckedDevice {
            get {
                return ResourceManager.GetString("CheckedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check value of.
        /// </summary>
        public static string CheckValue {
            get {
                return ResourceManager.GetString("CheckValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climatic.
        /// </summary>
        public static string Climatic {
            get {
                return ResourceManager.GetString("Climatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject num.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of non match.
        /// </summary>
        public static string CodeOfNonMatch {
            get {
                return ResourceManager.GetString("CodeOfNonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test conditions.
        /// </summary>
        public static string ConditionsOfTest {
            get {
                return ResourceManager.GetString("ConditionsOfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; and all its saved values ​​will be permanently deleted. Proceed?.
        /// </summary>
        public static string ConfirmationMessForDeleteManualInputParam {
            get {
                return ResourceManager.GetString("ConfirmationMessForDeleteManualInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constr..
        /// </summary>
        public static string Constructive {
            get {
                return ResourceManager.GetString("Constructive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create assembly protocol.
        /// </summary>
        public static string CreateAssemblyProtocol {
            get {
                return ResourceManager.GetString("CreateAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create devices.
        /// </summary>
        public static string CreateDevices {
            get {
                return ResourceManager.GetString("CreateDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create parameter.
        /// </summary>
        public static string CreateParameter {
            get {
                return ResourceManager.GetString("CreateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create value of manually entered parameter.
        /// </summary>
        public static string CreateValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("CreateValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current profile.
        /// </summary>
        public static string CurrentProfile {
            get {
                return ResourceManager.GetString("CurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered data contains an error..
        /// </summary>
        public static string DataContainsAnError {
            get {
                return ResourceManager.GetString("DataContainsAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loading failed.
        /// </summary>
        public static string DataLoadingFailed {
            get {
                return ResourceManager.GetString("DataLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data will not be saved..
        /// </summary>
        public static string DataWillNotBeSaved {
            get {
                return ResourceManager.GetString("DataWillNotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all filters.
        /// </summary>
        public static string DeleteAllFilters {
            get {
                return ResourceManager.GetString("DeleteAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system rejected the delete operation. The number of references to the deletion object is greater than zero..
        /// </summary>
        public static string DeleteCancelled {
            get {
                return ResourceManager.GetString("DeleteCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete column.
        /// </summary>
        public static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record.
        /// </summary>
        public static string DeleteCurrentRecord {
            get {
                return ResourceManager.GetString("DeleteCurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete parameter.
        /// </summary>
        public static string DeleteParameter {
            get {
                return ResourceManager.GetString("DeleteParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete permissions of user.
        /// </summary>
        public static string DeletePermissionsOfUser {
            get {
                return ResourceManager.GetString("DeletePermissionsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected records.
        /// </summary>
        public static string DeleteSelectedRecords {
            get {
                return ResourceManager.GetString("DeleteSelectedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete value of manually entered parameter.
        /// </summary>
        public static string DeleteValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("DeleteValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in english.
        /// </summary>
        public static string DescrEN {
            get {
                return ResourceManager.GetString("DescrEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of device parameters.
        /// </summary>
        public static string DescriptionOfDeviceParameters {
            get {
                return ResourceManager.GetString("DescriptionOfDeviceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in russian.
        /// </summary>
        public static string DescrRU {
            get {
                return ResourceManager.GetString("DescrRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy.
        /// </summary>
        public static string Destroy {
            get {
                return ResourceManager.GetString("Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string DeviceClass {
            get {
                return ResourceManager.GetString("DeviceClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement
        ///group comments.
        /// </summary>
        public static string DeviceComments {
            get {
                return ResourceManager.GetString("DeviceComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement group comments.
        /// </summary>
        public static string DeviceCommentsOneString {
            get {
                return ResourceManager.GetString("DeviceCommentsOneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device parameters.
        /// </summary>
        public static string DeviceParameters {
            get {
                return ResourceManager.GetString("DeviceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device reference editor.
        /// </summary>
        public static string DeviceReferenceEditor {
            get {
                return ResourceManager.GetString("DeviceReferenceEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References of devices norms.
        /// </summary>
        public static string DeviceReferences {
            get {
                return ResourceManager.GetString("DeviceReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type EN.
        /// </summary>
        public static string DeviceTypeEN {
            get {
                return ResourceManager.GetString("DeviceTypeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type RU.
        /// </summary>
        public static string DeviceTypeRU {
            get {
                return ResourceManager.GetString("DeviceTypeRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device identificator.
        /// </summary>
        public static string DevID {
            get {
                return ResourceManager.GetString("DevID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temperature mode of the displayed parameters and the selected profile do not match..
        /// </summary>
        public static string DifferentTemperatureModes {
            get {
                return ResourceManager.GetString("DifferentTemperatureModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist.
        /// </summary>
        public static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dU/dt.
        /// </summary>
        public static string dUdt {
            get {
                return ResourceManager.GetString("dUdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dU/dtMin.
        /// </summary>
        public static string dUdtMin {
            get {
                return ResourceManager.GetString("dUdtMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker: Edit assembly.
        /// </summary>
        public static string EditAssembly {
            get {
                return ResourceManager.GetString("EditAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit parameter.
        /// </summary>
        public static string EditParameter {
            get {
                return ResourceManager.GetString("EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit value of manually entered parameter.
        /// </summary>
        public static string EditValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("EditValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create.
        /// </summary>
        public static string FailedToCreate {
            get {
                return ResourceManager.GetString("FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter comparison type is not &apos;=&apos;..
        /// </summary>
        public static string FilterComparisonTypeIsNotEqual {
            get {
                return ResourceManager.GetString("FilterComparisonTypeIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by field &quot;{0}&quot; is off..
        /// </summary>
        public static string FilterIsNotOn {
            get {
                return ResourceManager.GetString("FilterIsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of filters on the field &quot;{0}&quot; is not equal to 1. To perform this action, no more than one filter on the field &quot;{0}&quot; is required..
        /// </summary>
        public static string FilterIsNotSingle {
            get {
                return ResourceManager.GetString("FilterIsNotSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of actived filters is not equal to 1. Only one filter is required to perform this action..
        /// </summary>
        public static string FiltersCountIsNotOne {
            get {
                return ResourceManager.GetString("FiltersCountIsNotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of filter values ​​for the field &quot;{0}&quot; is not equal to 1. To perform this action, no more than one filter value for the field &quot;{0}&quot; is required..
        /// </summary>
        public static string FilterValuesIsNotSingle {
            get {
                return ResourceManager.GetString("FilterValuesIsNotSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdrmMax.
        /// </summary>
        public static string IdrmMax {
            get {
                return ResourceManager.GetString("IdrmMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IgtMax.
        /// </summary>
        public static string IgtMax {
            get {
                return ResourceManager.GetString("IgtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In assembly protocol.
        /// </summary>
        public static string InAssemblyProtocol {
            get {
                return ResourceManager.GetString("InAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IrrmMax.
        /// </summary>
        public static string IrrmMax {
            get {
                return ResourceManager.GetString("IrrmMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of assembly protocols.
        /// </summary>
        public static string ListOfAssemblyProtocols {
            get {
                return ResourceManager.GetString("ListOfAssemblyProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data from database.
        /// </summary>
        public static string LoadDataFromDataBaseFault {
            get {
                return ResourceManager.GetString("LoadDataFromDataBaseFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with the data collected by means of MME hardware in the central database..
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage by self permissions.
        /// </summary>
        public static string ManageBySelfPermissions {
            get {
                return ResourceManager.GetString("ManageBySelfPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage device references.
        /// </summary>
        public static string ManageDeviceReferences {
            get {
                return ResourceManager.GetString("ManageDeviceReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions of user.
        /// </summary>
        public static string ManagePermissionsOfUser {
            get {
                return ResourceManager.GetString("ManagePermissionsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual add devices.
        /// </summary>
        public static string ManualAddDevices {
            get {
                return ResourceManager.GetString("ManualAddDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual entry profile.
        /// </summary>
        public static string ManualEntryProfile {
            get {
                return ResourceManager.GetString("ManualEntryProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual input param editor.
        /// </summary>
        public static string ManualInputParamEditor {
            get {
                return ResourceManager.GetString("ManualInputParamEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually entered parameters.
        /// </summary>
        public static string ManualInputParams {
            get {
                return ResourceManager.GetString("ManualInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MME.
        /// </summary>
        public static string MmeCode {
            get {
                return ResourceManager.GetString("MmeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode view.
        /// </summary>
        public static string ModeView {
            get {
                return ResourceManager.GetString("ModeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod..
        /// </summary>
        public static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter cannot be selected. The value of a parameter with the same name already exists in the editing object..
        /// </summary>
        public static string NameAlreadyExistsInObject {
            get {
                return ResourceManager.GetString("NameAlreadyExistsInObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editing object selected..
        /// </summary>
        public static string NoEditingObjectSelected {
            get {
                return ResourceManager.GetString("NoEditingObjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filters installed. Install at least one filter..
        /// </summary>
        public static string NoFiltersInstalled {
            get {
                return ResourceManager.GetString("NoFiltersInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission for this action..
        /// </summary>
        public static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max value of norms.
        /// </summary>
        public static string NormMaxValue {
            get {
                return ResourceManager.GetString("NormMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min value of norms.
        /// </summary>
        public static string NormMinValue {
            get {
                return ResourceManager.GetString("NormMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not created by hand.
        /// </summary>
        public static string NotCreatedByHand {
            get {
                return ResourceManager.GetString("NotCreatedByHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;  not found in SyteLine..
        /// </summary>
        public static string NotFoundInSL {
            get {
                return ResourceManager.GetString("NotFoundInSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не было выбрано..
        /// </summary>
        public static string NothingHasBeenSelected {
            get {
                return ResourceManager.GetString("NothingHasBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in assembly protocol.
        /// </summary>
        public static string NotInAssemblyProtocol {
            get {
                return ResourceManager.GetString("NotInAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not setted.
        /// </summary>
        public static string NotSetted {
            get {
                return ResourceManager.GetString("NotSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object for delete not selected..
        /// </summary>
        public static string ObjectForDeleteNotSelected {
            get {
                return ResourceManager.GetString("ObjectForDeleteNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnity.
        /// </summary>
        public static string Omnity {
            get {
                return ResourceManager.GetString("Omnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of range.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name not defined..
        /// </summary>
        public static string ParameterNameNotDefined {
            get {
                return ResourceManager.GetString("ParameterNameNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paremeter &apos;{0}&apos; is in use. The parameter can only be used once..
        /// </summary>
        public static string ParemeterIsInUse {
            get {
                return ResourceManager.GetString("ParemeterIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect or the DC user &apos;{0}&apos; does not exist.
        /// </summary>
        public static string PasswordIsIncorrect {
            get {
                return ResourceManager.GetString("PasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please authenticate..
        /// </summary>
        public static string PleaseAuthenticate {
            get {
                return ResourceManager.GetString("PleaseAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed record count {0}.
        /// </summary>
        public static string ProcessedRecordCount {
            get {
                return ResourceManager.GetString("ProcessedRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For {0} processing is not provided..
        /// </summary>
        public static string ProcessingIsNotProvided {
            get {
                return ResourceManager.GetString("ProcessingIsNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body of profile.
        /// </summary>
        public static string ProfileBody {
            get {
                return ResourceManager.GetString("ProfileBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile description.
        /// </summary>
        public static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile identificator.
        /// </summary>
        public static string ProfileID {
            get {
                return ResourceManager.GetString("ProfileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile of displayed data.
        /// </summary>
        public static string ProfileOfDisplayedData {
            get {
                return ResourceManager.GetString("ProfileOfDisplayedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol num.
        /// </summary>
        public static string ProtocolDescr {
            get {
                return ResourceManager.GetString("ProtocolDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrsmMin.
        /// </summary>
        public static string PrsmMin {
            get {
                return ResourceManager.GetString("PrsmMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qrr.
        /// </summary>
        public static string Qrr {
            get {
                return ResourceManager.GetString("Qrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QrrMax.
        /// </summary>
        public static string QrrMax {
            get {
                return ResourceManager.GetString("QrrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant..
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and create comment.
        /// </summary>
        public static string ReadCreateComment {
            get {
                return ResourceManager.GetString("ReadCreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading comments.
        /// </summary>
        public static string ReadingComments {
            get {
                return ResourceManager.GetString("ReadingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading the value of the &apos;Reason&apos; field.
        /// </summary>
        public static string ReadReason {
            get {
                return ResourceManager.GetString("ReadReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record date.
        /// </summary>
        public static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records:.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record successfully deleted.
        /// </summary>
        public static string RecordSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("RecordSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh   F5.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was found in the source data for building the report. Reason {0}..
        /// </summary>
        public static string ReportBuildingError {
            get {
                return ResourceManager.GetString("ReportBuildingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source data for building a report is empty. Report generation does not make sense..
        /// </summary>
        public static string ReportCannotBeGenerated {
            get {
                return ResourceManager.GetString("ReportCannotBeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RisolMin.
        /// </summary>
        public static string RisolMin {
            get {
                return ResourceManager.GetString("RisolMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string SapDescr {
            get {
                return ResourceManager.GetString("SapDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save was successful..
        /// </summary>
        public static string SaveWasSuccessful {
            get {
                return ResourceManager.GetString("SaveWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all records shown.
        /// </summary>
        public static string SelectAllRecords {
            get {
                return ResourceManager.GetString("SelectAllRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by number of records.
        /// </summary>
        public static string SelectByNumberOfRecords {
            get {
                return ResourceManager.GetString("SelectByNumberOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select DC user.
        /// </summary>
        public static string SelectDCUser {
            get {
                return ResourceManager.GetString("SelectDCUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected data is not for change..
        /// </summary>
        public static string SelectedDataIsNotForChange {
            get {
                return ResourceManager.GetString("SelectedDataIsNotForChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected parameter &apos;{0}&apos; is not deletable..
        /// </summary>
        public static string SelectedParameterIsNotDeletable {
            get {
                return ResourceManager.GetString("SelectedParameterIsNotDeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected parameter &apos;{0}&apos; is not editable. The value of this parameter can be obtained by measuring on equipment..
        /// </summary>
        public static string SelectedParameterIsNotEditable {
            get {
                return ResourceManager.GetString("SelectedParameterIsNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile.
        /// </summary>
        public static string SelectedProfile {
            get {
                return ResourceManager.GetString("SelectedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile parameters:.
        /// </summary>
        public static string SelectedProfileParameters {
            get {
                return ResourceManager.GetString("SelectedProfileParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected records deleted successfully..
        /// </summary>
        public static string SelectedRecordsDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SelectedRecordsDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected measurement groups was successfully moved to assembly protocol № {0}..
        /// </summary>
        public static string SelectedSuccessfullySendedToAssemblyProtocol {
            get {
                return ResourceManager.GetString("SelectedSuccessfullySendedToAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected to initialization state.
        /// </summary>
        public static string SelectedToInitState {
            get {
                return ResourceManager.GetString("SelectedToInitState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select job.
        /// </summary>
        public static string SelectGroupName {
            get {
                return ResourceManager.GetString("SelectGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile.
        /// </summary>
        public static string SelectProfile {
            get {
                return ResourceManager.GetString("SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send selected measurement groups to assembly protocol №.
        /// </summary>
        public static string SendSelectedToAssemblyProtocol {
            get {
                return ResourceManager.GetString("SendSelectedToAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user as admin.
        /// </summary>
        public static string SetAdministrator {
            get {
                return ResourceManager.GetString("SetAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set assembly protocol mode on.
        /// </summary>
        public static string SetAssemblyProtocolModeOn {
            get {
                return ResourceManager.GetString("SetAssemblyProtocolModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set comment for measurement group.
        /// </summary>
        public static string SetCommentForMeasurementGroup {
            get {
                return ResourceManager.GetString("SetCommentForMeasurementGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user permissions.
        /// </summary>
        public static string SetUserPermissions {
            get {
                return ResourceManager.GetString("SetUserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnity.
        /// </summary>
        public static string SiOmnity {
            get {
                return ResourceManager.GetString("SiOmnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string SiType {
            get {
                return ResourceManager.GetString("SiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string StateAssembly {
            get {
                return ResourceManager.GetString("StateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        public static string StateInitialization {
            get {
                return ResourceManager.GetString("StateInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly status.
        /// </summary>
        public static string StatusByAssemblyProtocol {
            get {
                return ResourceManager.GetString("StatusByAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; is {1}. Enter value of &quot;{0}&quot;..
        /// </summary>
        public static string SubjectNotSetted {
            get {
                return ResourceManager.GetString("SubjectNotSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition of temperature.
        /// </summary>
        public static string TemperatureCondition {
            get {
                return ResourceManager.GetString("TemperatureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tgt.
        /// </summary>
        public static string tgt {
            get {
                return ResourceManager.GetString("tgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TgtMax.
        /// </summary>
        public static string TgtMax {
            get {
                return ResourceManager.GetString("TgtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TjMax.
        /// </summary>
        public static string TjMax {
            get {
                return ResourceManager.GetString("TjMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tq.
        /// </summary>
        public static string tq {
            get {
                return ResourceManager.GetString("tq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TqMin.
        /// </summary>
        public static string TqMin {
            get {
                return ResourceManager.GetString("TqMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trr.
        /// </summary>
        public static string trr {
            get {
                return ResourceManager.GetString("trr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrrMin.
        /// </summary>
        public static string TrrMin {
            get {
                return ResourceManager.GetString("TrrMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Ts {
            get {
                return ResourceManager.GetString("Ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UbrMin.
        /// </summary>
        public static string UbrMin {
            get {
                return ResourceManager.GetString("UbrMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UdsmMin.
        /// </summary>
        public static string UdsmMin {
            get {
                return ResourceManager.GetString("UdsmMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UgtMax.
        /// </summary>
        public static string UgtMax {
            get {
                return ResourceManager.GetString("UgtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UisolMin.
        /// </summary>
        public static string UisolMin {
            get {
                return ResourceManager.GetString("UisolMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um.
        /// </summary>
        public static string Um {
            get {
                return ResourceManager.GetString("Um", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit measure is not defined..
        /// </summary>
        public static string UnitMeasureIsNotDefined {
            get {
                return ResourceManager.GetString("UnitMeasureIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature condition is unknown.
        /// </summary>
        public static string UnknownTemperatureCondition {
            get {
                return ResourceManager.GetString("UnknownTemperatureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck the all records shown.
        /// </summary>
        public static string UnSelectAllRecords {
            get {
                return ResourceManager.GetString("UnSelectAllRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrsmMin.
        /// </summary>
        public static string UrsmMin {
            get {
                return ResourceManager.GetString("UrsmMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User credentials.
        /// </summary>
        public static string UserCredentials {
            get {
                return ResourceManager.GetString("UserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is not an application user &apos;{1}&apos;.
        /// </summary>
        public static string UserIisNotAnApplicationUser {
            get {
                return ResourceManager.GetString("UserIisNotAnApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User selected.
        /// </summary>
        public static string UserSelected {
            get {
                return ResourceManager.GetString("UserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Usr {
            get {
                return ResourceManager.GetString("Usr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UtmCorrection.
        /// </summary>
        public static string UtmCorrection {
            get {
                return ResourceManager.GetString("UtmCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UtmMax.
        /// </summary>
        public static string UtmMax {
            get {
                return ResourceManager.GetString("UtmMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value not selected, or not correct.
        /// </summary>
        public static string ValueIsNotGood {
            get {
                return ResourceManager.GetString("ValueIsNotGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not an integer.
        /// </summary>
        public static string ValueIsNotInteger {
            get {
                return ResourceManager.GetString("ValueIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of manually entered parameter.
        /// </summary>
        public static string ValueOfManuallyEnteredParam {
            get {
                return ResourceManager.GetString("ValueOfManuallyEnteredParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with assembly protocol.
        /// </summary>
        public static string WorkWithAssemblyProtocol {
            get {
                return ResourceManager.GetString("WorkWithAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with comments.
        /// </summary>
        public static string WorkWithComments {
            get {
                return ResourceManager.GetString("WorkWithComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with device references.
        /// </summary>
        public static string WorkWithDeviceReferences {
            get {
                return ResourceManager.GetString("WorkWithDeviceReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with manually entered parameters.
        /// </summary>
        public static string WorkWithManualInputParams {
            get {
                return ResourceManager.GetString("WorkWithManualInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with params of assembly protocol.
        /// </summary>
        public static string WorkWithManualParamsOfAssemblyProtocol {
            get {
                return ResourceManager.GetString("WorkWithManualParamsOfAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with value of manually entered parameter.
        /// </summary>
        public static string WorkWithValueOfManualInputParam {
            get {
                return ResourceManager.GetString("WorkWithValueOfManualInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong description.
        /// </summary>
        public static string WrongDescription {
            get {
                return ResourceManager.GetString("WrongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter was not created. The thermal conditions of the measurements and the created parameter do not match..
        /// </summary>
        public static string WrongTermalConditions {
            get {
                return ResourceManager.GetString("WrongTermalConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not match the mask &apos;{1}&apos;..
        /// </summary>
        public static string WrongValueByMask {
            get {
                return ResourceManager.GetString("WrongValueByMask", resourceCulture);
            }
        }
    }
}
